name: tictactoe_xo_royale
description: "A premium Tic Tac Toe mobile game with modern UI/UX and Material 3 design"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_riverpod: ^3.0.1
  riverpod_annotation: ^3.0.1

  # Navigation
  go_router: ^16.2.4
  
  # UI & Animations
  flutter_animate: ^4.5.2
  google_fonts: ^6.3.2
  
  # Audio & Haptics
  just_audio: ^0.10.5
  vibration: ^3.1.4
  
  # Storage & Data
  dio: ^5.9.0

  # Drift Database
  drift: ^2.28.2
  sqlite3_flutter_libs: ^0.5.40
  drift_flutter: ^0.2.7

  
  # Utilities
  equatable: ^2.0.5
  collection: ^1.19.1
  intl: ^0.20.2
  path: ^1.9.1
  
  # Device Info
  device_info_plus: ^12.1.0
  package_info_plus: ^9.0.0
  
  # Code Generation
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.7.1
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  riverpod_generator: ^3.0.1
  drift_dev: ^2.28.3
  
  # Linting
  riverpod_lint: ^3.0.1

  matcher: any
flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/audio/
    - assets/fonts/
  
  # Fonts
  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-VariableFont_wght.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-VariableFont_wght.ttf

